# Mozilla User Preferences

/* Do not edit this file.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */
pref("extensions.termblaster@forizon.com.opened.database", "chrome://termblaster/content/data/services.tbd");
pref("extensions.termblaster@forizon.com.opened.terms", "");
pref("extensions.termblaster@forizon.com.places.folder", -1);
pref("extensions.termblaster@forizon.com.places.quickTag", "termblaster quick");
pref("extensions.termblaster@forizon.com.terms.showConfirm", true);
pref("extensions.termblaster@forizon.com.destination", 1);
pref("extensions.termblaster@forizon.com.quote", false);
pref("extensions.termblaster@forizon.com.focus", false);
pref("extensions.termblaster@forizon.com.context.quicklistFolder", true);
pref("extensions.termblaster@forizon.com.debug", false);

pref("extensions.termblaster@forizon.com.description", "chrome://termblaster/locale/termblaster.properties");