# Mozilla User Preferences

/* Do not edit this file.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */
pref("extensions.termblaster.opened.database", "chrome://termblaster/content/data/Services.tbd");
pref("extensions.termblaster.opened.quicklist", "chrome://termblaster/content/data/QuickList.tbq");
pref("extensions.termblaster.opened.terms", "");
pref("extensions.termblaster.terms.showConfirm", true);
pref("extensions.termblaster.destination", 1);
pref("extensions.termblaster.quote", false);
pref("extensions.termblaster.focus", false);
pref("extensions.termblaster.context.databaseFolder", false);
pref("extensions.termblaster.context.quicklistFolder", true);
pref("extensions.termblaster.debug", false);

pref("extensions.termblaster@forizon.com.description", "chrome://termblaster/locale/termblaster.properties");
